import { execFile } from "node:child_process";
import { access, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import ignore from "ignore";

const execFileAsync = promisify(execFile);

async function pathExists(p: string): Promise<boolean> {
  return access(p).then(
    () => true,
    () => false,
  );
}

export async function findGitRoot(
  startDir: string,
): Promise<string | undefined> {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["rev-parse", "--show-toplevel"],
      { cwd: startDir },
    );
    const root = stdout.trim();
    return root.length > 0 ? root : undefined;
  } catch {
    return undefined;
  }
}

export async function isGitRepo(cwd: string): Promise<boolean> {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["rev-parse", "--is-inside-work-tree"],
      { cwd },
    );
    return stdout.trim() === "true";
  } catch {
    return false;
  }
}

const ENV_FILENAME = ".env.braintrust";
const BRAINTRUST_JSON_FILENAME = ".braintrust.json";
const GENERATED_FILE_COMMENT =
  "This file was generated by the Braintrust CLI wizard. This file contains sensitive information. Do not commit this file to version control! The file can be safely deleted after confirming your application sends traces.";
const LOCAL_TOKEN_FILENAMES = [ENV_FILENAME, BRAINTRUST_JSON_FILENAME] as const;

export function envBraintrustPath(directory: string): string {
  return join(directory, ENV_FILENAME);
}

export function braintrustJsonPath(directory: string): string {
  return join(directory, BRAINTRUST_JSON_FILENAME);
}

export async function envBraintrustExists(directory: string): Promise<boolean> {
  return pathExists(envBraintrustPath(directory));
}

export async function braintrustTokenFilesExist(
  directory: string,
): Promise<boolean> {
  return (
    (await pathExists(envBraintrustPath(directory))) ||
    (await pathExists(braintrustJsonPath(directory)))
  );
}

export type EnvFileWriteResult = {
  readonly envFilePath: string;
  readonly braintrustJsonFilePath: string;
  readonly gitignorePath: string;
  readonly addedToGitignore: boolean;
  readonly alreadyCovered: boolean;
};

export async function writeEnvBraintrust(
  directory: string,
  apiKey: string,
): Promise<EnvFileWriteResult> {
  const envFilePath = envBraintrustPath(directory);
  const braintrustJsonFilePath = braintrustJsonPath(directory);

  await writeFile(
    envFilePath,
    `# ${GENERATED_FILE_COMMENT}\nBRAINTRUST_API_KEY=${apiKey}\n`,
    {
      mode: 0o600,
    },
  );
  await writeFile(
    braintrustJsonFilePath,
    `${JSON.stringify(
      {
        "//": GENERATED_FILE_COMMENT,
        BRAINTRUST_API_KEY: apiKey,
      },
      null,
      2,
    )}\n`,
    {
      mode: 0o600,
    },
  );

  const gitignoreResult = await ensureEnvBraintrustIgnored(directory);
  return {
    envFilePath,
    braintrustJsonFilePath,
    ...gitignoreResult,
  };
}

export async function ensureEnvBraintrustIgnored(
  directory: string,
): Promise<Omit<EnvFileWriteResult, "envFilePath" | "braintrustJsonFilePath">> {
  const gitignorePath = join(directory, ".gitignore");
  const existing = (await pathExists(gitignorePath))
    ? await readFile(gitignorePath, "utf8")
    : "";

  const missingFilenames = LOCAL_TOKEN_FILENAMES.filter(
    (filename) => !gitignoreCovers(existing, filename),
  );
  if (missingFilenames.length === 0) {
    return {
      gitignorePath,
      addedToGitignore: false,
      alreadyCovered: true,
    };
  }

  const sep = existing.length === 0 || existing.endsWith("\n") ? "" : "\n";
  await writeFile(
    gitignorePath,
    `${existing}${sep}# Added by Braintrust Wizard\n${missingFilenames.join("\n")}\n`,
  );
  return {
    gitignorePath,
    addedToGitignore: true,
    alreadyCovered: false,
  };
}

export function gitignoreCovers(content: string, filename: string): boolean {
  return ignore().add(content).ignores(filename);
}
