name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./.github/actions/setup

      - name: Build CLIs
        run: pnpm build

  build-binary:
    name: Build binaries
    uses: ./.github/workflows/build-binaries.yml

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./.github/actions/setup

      - name: Run ESLint
        run: pnpm lint

  format:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./.github/actions/setup

      - name: Check formatting
        run: pnpm format:check
